### ISSUE TITLE
cannot import name 'CloudWatchLogs' from 'deepracer.logs'

### ISSUE THREAD

**Issue by mdavis-xyz** [aws-deepracer-community/deepracer-analysis#22] opened 2021-06-20 09:14 UTC
I just tried running the first notebook, and it didn't work for me.

[this line](https://github.com/aws-deepracer-community/deepracer-analysis/blob/53aa6db43ffbbcfda78e1cf9c71e589cce8643a5/ActionSpace_analysis.py#L56) failed.

# Steps to reproduce

I'm on a macbook (Big Sur). 

```
git clone ...
cd ...
bin/build-docker-image.sh
bin/start.sh lab
bin/open-notebook.sh
```

That last command failed, so I did PR #21 .

I openned a browser. Then openned `ActionSpace_analysis.ipynb` inside Jupyter, and ran all cells.

# Expected behavior

The `import`s should all pass.

# Actual behavior.

In cell:

```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
​
from deepracer.tracks import TrackIO, Track
#from deepracer.tracks.track_utils import track_breakdown
from deepracer.logs import CloudWatchLogs as cw, \
    SimulationLogsIO as slio, \
    PlottingUtils as pu,\
    AnalysisUtils as au   #, \
    #   ActionBreakdownUtils as abu,\
    #   NewRewardUtils as nr, \ 
```

I got error:

```
​# Ignore deprecation warnings we have no power over
import warnings
warnings.filterwarnings('ignore')
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-d439cd8ebbb0> in <module>
      6 from deepracer.tracks import TrackIO, Track
      7 #from deepracer.tracks.track_utils import track_breakdown
----> 8 from deepracer.logs import CloudWatchLogs as cw, \
      9     SimulationLogsIO as slio, \
     10     PlottingUtils as pu,\

ImportError: cannot import name 'CloudWatchLogs' from 'deepracer.logs' (/opt/conda/lib/python3.9/site-packages/deepracer/logs/__init__.py)
```

I don't see any file or folder called `deepracer`.

**Comment by larsll** [comment] 2022-06-11 21:11
This is a duplicate of #13

**Closed as completed by larsll** 2022-06-11 21:11 UTC
Labels: bug
